name = "tranoptim"
compatibility_date = "2023-06-18"
node_compat = true

[vars]
# 这里是默认环境变量，实际部署时会被Cloudflare仪表盘中的值覆盖
PORT = "8788"
# 认证相关配置
AUTH_ENABLED = "true"
# 认证用户列表（JSON字符串格式）
AUTH_USERS = '{"admin": "admin123", "user1": "password123", "demo": "demo2024"}'

# 可在Cloudflare仪表盘设置以下密钥环境变量
# OPENAI_API_KEY = "your_openai_api_key"
# GEMINI_API_KEY = "your_gemini_api_key"
# DEEPSEEK_API_KEY = "your_deepseek_api_key"
# QWEN_API_KEY = "your_qwen_api_key"
# DOUBAO_API_KEY = "your_doubao_api_key" 